export const dateRules = [
  {
    start: new Date("2025-09-24T00:00:00+07:00").getTime(),
    end: new Date("2025-09-28T00:00:00+07:00").getTime(),
    redirectTo: "/main/:kelompok",
  },
  {
    start: new Date("2025-09-26T08:00:00+07:00").getTime(),
    end: new Date("2025-09-28T16:50:00+07:00").getTime(),
    redirectTo: "/group/:kelompok",
  },
  {
    start: new Date("2025-09-26T08:00:00+07:00").getTime(),
    end: new Date("2025-09-28T16:50:00+07:00").getTime(),
    redirectTo: "/group/:kelompok/squad",
  },
];

export const listGroup = {
  "f47ac10b-58cc-4372-a567-0e02b2c3d479": {
    name: "CRYO",
    listName: [
      "AHMAD MAULANA FAQIH",
      "DODY ANGGAH SAPUTRO, S.FARM",
      "GANA MAHADI",
      "TJHIA LIAN NIE",
      "KEISHA",
      "MOCH. KHOIRUL ANAM",
      "STEFANI AJENG FEBRIYANTI",
      "FATICHA NASHARO QISTHIA FARID",
      "JESIKA CAROLINE",
    ],
  },
  "9c858901-8a57-4791-81fe-4c455b099bc9": {
    name: "KYNTARA",
    listName: [
      "AISA NAZIAH",
      "FAHRIZA GULHAM YUSUP",
      "IIN SAPUTRA",
      "KEVIN FEBRIANUS MODA",
      "LINDA NOVIANA PANJAITAN",
      "MUHAMMAD FAHRIZAL KHOIRI",
      "RUKTININGSIH",
      "STEPHANIE SUNANDAR",
      "BRIGITA IVANA",
    ],
  },
  "16fd2706-8baf-433b-82eb-8c7fada847da": {
    name: "BIO-GF",
    listName: [
      "SURYA DHARMA",
      "HASNA HAMIDAH",
      "OSWALD DEW",
      "MAISYA HANIFAH",
      "MATHEUS ALVIN PRAWIRA",
      "MELLY YANA SILVI",
      "MUHAMMAD LUTHFAN MAULANA",
      "MUHAMMAD MA’RIF",
      "MUHAMMAD RYO",
    ],
  },
  "7c9e6679-7425-40de-944b-e07fc1f90ae7": {
    name: "KALSTEM",
    listName: [
      "DR. ADELINE",
      "FERI IRWANSYAH",
      "LAVINIA IDOLA",
      "MUHAMMAD PAJAR",
      "NATHANAEL",
      "SAKINAH",
      "STEFAN NUGROHO",
      "HILDA NURMALILHAH",
    ],
  },
  "123e4567-e89b-12d3-a456-426614174000": {
    name: "EXOSOME",
    listName: [
      "EVI NURSAEPI",
      "FERRY BOY PRATAMA SINAGA",
      "HIKMAHWATI",
      "MICHELLINA YUNARDY",
      "JIMMY SUSANTO",
      "SONYA APRIANI TANDY",
      "TAUFIK IKHWANA DJIBRAN PRAMUDYA",
      "IRENE NATALIA NESTA SIHOMBING",
    ],
  },
  "550e8400-e29b-41d4-a716-446655440000": {
    name: "ORACLE",
    listName: [
      "ALEXANDER BENNY PRADIPTA",
      "ANTONIUS TEGUH IMAN SANTOSO",
      "ANTON HIDAYAT",
      "HANSLIBRERY SIMANJUNTAK",
      "INE ISLAMIATI",
      "SALMA SAPANA MEDIANA P",
      "VERONIKA ELLENA",
      "FREDERICK LIWANG",
    ],
  },
  "6fa459ea-ee8a-3ca4-894e-db77e160355e": {
    name: "HYPERSTACK",
    listName: [
      "AURIGA RAFSANDJANIE",
      "FERI PURWO NUGROHO",
      "IKA RIZKY FADHILLAH",
      "WIDYANTI OEY",
      "PANGGALIH SAKO DENTA",
      "STEFEN MULIAWAN",
      "WARA NOVEKA",
      "FEBRI ROMANDA",
    ],
  },
  "c9bf9e57-1685-4c89-bafb-ff5af830be8a": {
    name: "WCB",
    listName: [
      "AGUS SURANTO",
      "BINTANG TEDJO BAGASKARA",
      "LARA YUPA. ME",
      "SUNANTO",
      "SANDY QLINTANG",
      "JEFRI EFRANDA",
      "WIDIA MELIAWATI",
      "NOVELIA ANNA",
    ],
  },
  "3d813cbb-47fb-32ba-91df-831e1593ac29": {
    name: "LUCM",
    listName: [
      "ANGGARA DAMAR RADYASTAMA",
      "AZKA RASHIFAH",
      "BRANDON CHRISTOPHER",
      "MARCHELLA DEWI PURWATI",
      "ZAKARIA RAMADHAN",
      "ZIKRY FARIZ HIDAYAT",
      "R. HARRY MURTI",
      "MATTHEW MARVELINO",
    ],
  },
  "e02fd0e4-00fd-090A-ca30-0d00a0038ba0": {
    name: "RUCM",
    listName: [
      "BRIGITTA GLORIA TJAHJADI",
      "DEVIANA KARTIKA",
      "DHIMAS RAIHAN SURYAMAHENDRA PUTRO",
      "GERRY SUSANTO",
      "GRACE CHRISTY",
      "MICHELE LIONY MARIA ONIBALA",
      "VINI GOKKANA CLARA MANURUNG",
      "BAMBANG HADY PRABOWO",
      "MARCELINUS BARLIAN",
    ],
  },
};
